DROP TABLE IF EXISTS faq;

CREATE TABLE faq (
    faq_no SERIAL PRIMARY KEY,

    category VARCHAR(30) NOT NULL,
    question VARCHAR(200) NOT NULL,
    answer TEXT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);