GRANT USAGE ON SCHEMA public TO bono_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bono_user;

GRANT ALL PRIVILEGES
ON ALL SEQUENCES IN SCHEMA public
TO bono_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO bono_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO bono_user;
