package api.a_security_config;
import api.a_filter.JwtUtil; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.http.ResponseEntity; import org.springframework.security.crypto.password.PasswordEncoder; import java.util.Map; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class LoginControllerTest {
 @Mock AuthService authService; @Mock PasswordEncoder passwordEncoder; @Mock JwtUtil jwtUtil; @InjectMocks LoginController controller;
 @Test @DisplayName("UT-BE-LOGIN-CTRL-001 정상 계정은 JWT와 사용자 ID를 반환한다") void success(){ LoginDTO request=new LoginDTO(); request.setLoginId("user"); request.setLoginPwd("pw"); LoginDTO saved=user("user","encoded","RESIDENT","ACTIVE"); when(authService.getUserInfo("user")).thenReturn(saved); when(passwordEncoder.matches("pw","encoded")).thenReturn(true); when(jwtUtil.createToken("user","RESIDENT","ACTIVE")).thenReturn("token"); Map<?,?> result=(Map<?,?>)controller.login(request); assertThat(result.get("token")).isEqualTo("token"); assertThat(result.get("userId")).isEqualTo("user"); }
 @Test @DisplayName("UT-BE-LOGIN-CTRL-002 없는 계정은 401을 반환한다") void missing(){ LoginDTO d=new LoginDTO(); d.setLoginId("none"); assertThat(((ResponseEntity<?>)controller.login(d)).getStatusCode().value()).isEqualTo(401); verifyNoInteractions(passwordEncoder,jwtUtil); }
 @Test @DisplayName("UT-BE-LOGIN-CTRL-003 비밀번호 불일치는 401을 반환한다") void wrongPassword(){ LoginDTO d=new LoginDTO(); d.setLoginId("user"); d.setLoginPwd("bad"); when(authService.getUserInfo("user")).thenReturn(user("user","encoded","RESIDENT","ACTIVE")); when(passwordEncoder.matches("bad","encoded")).thenReturn(false); assertThat(((ResponseEntity<?>)controller.login(d)).getStatusCode().value()).isEqualTo(401); verifyNoInteractions(jwtUtil); }
 @Test @DisplayName("UT-BE-LOGIN-CTRL-004 비활성 계정은 403을 반환한다") void inactive(){ LoginDTO d=new LoginDTO(); d.setLoginId("user"); d.setLoginPwd("pw"); when(authService.getUserInfo("user")).thenReturn(user("user","encoded","RESIDENT","INACTIVE")); when(passwordEncoder.matches("pw","encoded")).thenReturn(true); assertThat(((ResponseEntity<?>)controller.login(d)).getStatusCode().value()).isEqualTo(403); verifyNoInteractions(jwtUtil); }
 private LoginDTO user(String id,String pwd,String role,String status){ LoginDTO d=new LoginDTO(); d.setLoginId(id); d.setLoginPwd(pwd); d.setRole(role); d.setMemStatus(status); return d; }
}
