package api.robot_pdm_p;
import api.predictive_maintenance_p.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import java.util.List; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class RobotPdmServiceTest {
 @Mock RobotPdmMapper mapper; @Mock PredictiveMaintenanceClient client; @Mock PdmActionAuthorizationService auth; @InjectMocks RobotPdmService service;
 @Test @DisplayName("UT-BE-ROBOT-PDM-001 예측 목록을 반환한다") void list(){ RobotPdmDTO d=new RobotPdmDTO(); when(mapper.list()).thenReturn(List.of(d)); assertThat(service.list()).containsExactly(d); }
 @Test @DisplayName("UT-BE-ROBOT-PDM-002 예측 상세를 반환한다") void detail(){ RobotPdmDTO d=new RobotPdmDTO(); when(mapper.detail(1)).thenReturn(d); assertThat(service.detail(1)).isSameAs(d); }
 @Test @DisplayName("UT-BE-ROBOT-PDM-003 예측을 직접 저장한다") void save(){ RobotPdmDTO d=new RobotPdmDTO(); when(mapper.savePrediction(d)).thenReturn(1); assertThat(service.savePrediction(d)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-ROBOT-PDM-004 단건 정상 분석을 최신·최근 이력에 반영한다") void analyzeOne(){ PredictiveMaintenanceResponseDTO r=normal("ROBOT-01"); when(client.predictNextRobot()).thenReturn(r); assertThat(service.analyzeOne()).isSameAs(r); assertThat(service.getLatestPredictions()).hasSize(1); assertThat(service.getRecentPredictions(1)).hasSize(1); }
 @Test @DisplayName("UT-BE-ROBOT-PDM-005 일괄 분석 응답이 없으면 빈 목록을 반환한다") void nullAll(){ when(client.predictNextRobots()).thenReturn(null); assertThat(service.analyzeAll()).isEmpty(); }
 @Test @DisplayName("UT-BE-ROBOT-PDM-006 일괄 분석 결과를 모두 최신 이력에 반영한다") void analyzeAll(){ List<PredictiveMaintenanceResponseDTO> responses=List.of(normal("ROBOT-01"),normal("ROBOT-02")); when(client.predictNextRobots()).thenReturn(responses); assertThat(service.analyzeAll()).isSameAs(responses); assertThat(service.getLatestPredictions()).hasSize(2); }
 @Test @DisplayName("UT-BE-ROBOT-PDM-007 주의 결과를 즉시 저장하고 조치 알림을 보낸다") void warning(){ PredictiveMaintenanceResponseDTO r=normal("ROBOT-01"); r.setRiskLevel("주의"); r.setActionRequired(true); when(client.predictNextRobot()).thenReturn(r); when(mapper.savePrediction(any())).thenReturn(1); service.analyzeOne(); verify(mapper).savePrediction(any()); verify(auth).sendDangerAlert(contains("ROBOT_01"),anyMap()); }
 @Test @DisplayName("UT-BE-ROBOT-PDM-008 시간별 저장은 최신 정상 결과만 저장한다") void hourly(){ when(client.predictNextRobot()).thenReturn(normal("ROBOT-01")); service.analyzeOne(); service.saveHourlyNormalPredictions(); verify(mapper).savePrediction(argThat(d -> d.getRobotNo()==1)); }
 @Test @DisplayName("UT-BE-ROBOT-PDM-009 메모리 예측 이력 초기값은 빈 목록이다") void emptyMemory(){ assertThat(service.getLatestPredictions()).isEmpty(); assertThat(service.getRecentPredictions(1)).isEmpty(); }
 @Test @DisplayName("UT-BE-ROBOT-PDM-010 지원하지 않는 로봇 이력 조회를 거부한다") void invalidRecent(){ assertThatThrownBy(() -> service.getRecentPredictions(0)).isInstanceOf(IllegalArgumentException.class); assertThatThrownBy(() -> service.getRecentPredictions(9)).isInstanceOf(IllegalArgumentException.class); }
 @Test @DisplayName("UT-BE-ROBOT-PDM-011 위험 예측 조치를 완료하고 최신값을 갱신한다") void complete(){ RobotPdmDTO target=new RobotPdmDTO(); target.setRobotNo(1); target.setRiskLevel("위험"); target.setActionStatus("ACTION_REQUIRED"); RobotPdmDTO done=new RobotPdmDTO(); done.setRobotNo(1); when(mapper.detail(9)).thenReturn(target,done); when(auth.requireMemberNo("admin")).thenReturn(7); when(auth.normalizeActionNote(" 점검 ")).thenReturn("점검"); when(mapper.completeAction(9,7,"점검")).thenReturn(1); assertThat(service.completeAction(9," 점검 ","admin")).isSameAs(done); verify(client).completeRobotAction(1); }
 @Test @DisplayName("UT-BE-ROBOT-PDM-012 없는·비정상 대상과 중복 조치 완료를 거부한다") void completeFailures(){ assertThatThrownBy(() -> service.completeAction(9,"점검","admin")).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); RobotPdmDTO normal=new RobotPdmDTO(); normal.setRiskLevel("정상"); normal.setActionStatus("NOT_REQUIRED"); when(mapper.detail(9)).thenReturn(normal); assertThatThrownBy(() -> service.completeAction(9,"점검","admin")).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); RobotPdmDTO danger=new RobotPdmDTO(); danger.setRobotNo(1); danger.setRiskLevel("위험"); danger.setActionStatus("ACTION_REQUIRED"); when(mapper.detail(9)).thenReturn(danger); when(auth.requireMemberNo("admin")).thenReturn(7); when(auth.normalizeActionNote("점검")).thenReturn("점검"); when(mapper.completeAction(9,7,"점검")).thenReturn(0); assertThatThrownBy(() -> service.completeAction(9,"점검","admin")).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); }
 private PredictiveMaintenanceResponseDTO normal(String no){ PredictiveMaintenanceResponseDTO r=new PredictiveMaintenanceResponseDTO(); r.setEquipmentNo(no); r.setRiskLevel("정상"); r.setRiskProbability(.9); r.setProbabilities(java.util.Map.of("정상",.9,"주의",.08,"위험",.02)); r.setSensorValues(java.util.Map.of()); r.setPredictedAt(java.time.LocalDateTime.now()); return r; }
}
