package api.vehicle_p;
import api.mem_purchase_p.MemPurchaseService; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.web.server.ResponseStatusException; import java.time.LocalDateTime; import java.util.List; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class VehicleServiceTest {
 @Mock VehicleMapper vehicleMapper; @Mock MemPurchaseService memPurchaseService; @InjectMocks VehicleService service;
 @Test @DisplayName("UT-BE-VEHICLE-001 관리자 차량 목록을 조회한다") void list(){ List<VehicleDTO>x=List.of(); when(vehicleMapper.list(null)).thenReturn(x); assertThat(service.listservice()).isSameAs(x); }
 @Test @DisplayName("UT-BE-VEHICLE-002 검색 조건을 표준화해 회원 차량을 검색한다") void search(){ service.search(" Visit "," resident "); verify(vehicleMapper).search("visit","RESIDENT"); service.search(null,null); verify(vehicleMapper).search("",""); }
 @Test @DisplayName("UT-BE-VEHICLE-003 입주민 본인 차량 목록을 조회한다") void residentList(){ List<VehicleDTO>x=List.of(new VehicleDTO()); when(vehicleMapper.list("user")).thenReturn(x); assertThat(service.residentList("user")).isSameAs(x); }
 @Test @DisplayName("UT-BE-VEHICLE-004 월 방문 신청시간을 조회한다") void monthlyUsed(){ when(vehicleMapper.sumMonthlyRequestedVisitMinutesByLoginId("user")).thenReturn(120); assertThat(service.getMonthlyRegisteredVisitCount("user")).isEqualTo(120); }
 @Test @DisplayName("UT-BE-VEHICLE-005 기본 무료시간과 구매시간으로 월 한도를 계산한다") void monthlyLimit(){ when(memPurchaseService.getMonthlyPaidVisitQuantity("user")).thenReturn(60); assertThat(service.getMonthlyVisitLimitCount("user")).isEqualTo(9060); }
 @Test @DisplayName("UT-BE-VEHICLE-006 관리자가 차량번호·종류를 정리해 승인 차량을 등록한다") void adminRequest(){ VehicleDTO d=adminVehicle(); d.setCarNo("12 가 3456"); d.setVehicleType(" NORMAL "); when(vehicleMapper.insert(null,d)).thenReturn(1); assertThat(service.adminRequest(d)).isEqualTo(1); assertThat(d.getCarNo()).isEqualTo("12가3456"); assertThat(d.getVehicleType()).isEqualTo("normal"); assertThat(d.getVehicleStatus()).isEqualTo("APPROVED"); }
 @Test @DisplayName("UT-BE-VEHICLE-007 관리자 등록은 차량번호·유형·회원·기간 오류를 거부한다") void adminRequestInputFailures(){ VehicleDTO blankCar=adminVehicle(); blankCar.setCarNo(" "); assertThatThrownBy(()->service.adminRequest(blankCar)).isInstanceOf(ResponseStatusException.class); VehicleDTO invalidType=adminVehicle(); invalidType.setVehicleType("bad"); assertThatThrownBy(()->service.adminRequest(invalidType)).isInstanceOf(ResponseStatusException.class); VehicleDTO noMember=adminVehicle(); noMember.setMemberNo(null); assertThatThrownBy(()->service.adminRequest(noMember)).isInstanceOf(ResponseStatusException.class); VehicleDTO badDate=adminVehicle(); badDate.setEndDate(badDate.getStartDate()); assertThatThrownBy(()->service.adminRequest(badDate)).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-VEHICLE-008 관리자 등록은 중복 차량과 일반차량 2대 초과를 거부한다") void adminRequestConflicts(){ VehicleDTO d=adminVehicle(); when(vehicleMapper.countActiveByCarNo("12가3456")).thenReturn(1); assertThatThrownBy(()->service.adminRequest(d)).isInstanceOf(ResponseStatusException.class); when(vehicleMapper.countActiveByCarNo("12가3456")).thenReturn(0); when(vehicleMapper.countActiveNormalByMemberNo(1)).thenReturn(2); assertThatThrownBy(()->service.adminRequest(d)).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-VEHICLE-009 관리실 방문차량을 30분 등록하고 생성번호를 반환한다") void adminVisit(){ stubGeneratedInsert(11); assertThat(service.registerAdminVisit("admin","12가 3456")).isEqualTo(11); verify(vehicleMapper).insert(eq("admin"),argThat(d->d.getEndDate().equals(d.getStartDate().plusMinutes(30)))); }
 @Test @DisplayName("UT-BE-VEHICLE-010 관리실 방문차량은 중복·저장 실패를 거부한다") void adminVisitFailures(){ when(vehicleMapper.countActiveByCarNo("12가3456")).thenReturn(1); assertThatThrownBy(()->service.registerAdminVisit("admin","12가3456")).isInstanceOf(ResponseStatusException.class); when(vehicleMapper.countActiveByCarNo("12가3456")).thenReturn(0); assertThatThrownBy(()->service.registerAdminVisit("admin","12가3456")).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-VEHICLE-011 긴급차량을 72시간 등록하고 생성번호를 반환한다") void emergencyVisit(){ stubGeneratedInsert(12); assertThat(service.registerEmergencyVisit("admin","34나5678")).isEqualTo(12); verify(vehicleMapper).insert(eq("admin"),argThat(d->d.getEndDate().equals(d.getStartDate().plusHours(72)))); }
 @Test @DisplayName("UT-BE-VEHICLE-012 긴급차량은 중복·저장 실패를 거부한다") void emergencyVisitFailures(){ when(vehicleMapper.countActiveByCarNo("34나5678")).thenReturn(1); assertThatThrownBy(()->service.registerEmergencyVisit("admin","34나5678")).isInstanceOf(ResponseStatusException.class); when(vehicleMapper.countActiveByCarNo("34나5678")).thenReturn(0); assertThatThrownBy(()->service.registerEmergencyVisit("admin","34나5678")).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-VEHICLE-013 입주민 방문차량을 월 한도 안에서 등록한다") void residentVisit(){ VehicleDTO d=visit(2,2); when(vehicleMapper.insert("user",d)).thenReturn(1); assertThat(service.residentVisitRequest("user",d)).isEqualTo(1); assertThat(d.getVehicleStatus()).isEqualTo("APPROVED"); }
 @Test @DisplayName("UT-BE-VEHICLE-014 입주민 방문신청은 시작시간과 1시간 단위·24시간 한계를 검사한다") void residentVisitDateFailures(){ VehicleDTO early=visit(0,2); assertThatThrownBy(()->service.residentVisitRequest("user",early)).isInstanceOf(ResponseStatusException.class); VehicleDTO half=visitMinutes(2,90); assertThatThrownBy(()->service.residentVisitRequest("user",half)).isInstanceOf(ResponseStatusException.class); VehicleDTO longVisit=visit(2,25); assertThatThrownBy(()->service.residentVisitRequest("user",longVisit)).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-VEHICLE-015 입주민 방문신청은 월 한도 초과와 중복 차량을 거부한다") void residentVisitConflicts(){ VehicleDTO d=visit(2,2); when(vehicleMapper.sumMonthlyRequestedVisitMinutesByLoginId("user")).thenReturn(8990); assertThatThrownBy(()->service.residentVisitRequest("user",d)).isInstanceOf(ResponseStatusException.class); when(vehicleMapper.sumMonthlyRequestedVisitMinutesByLoginId("user")).thenReturn(0); when(vehicleMapper.countActiveByCarNo("12가3456")).thenReturn(1); assertThatThrownBy(()->service.residentVisitRequest("user",d)).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-VEHICLE-016 차량을 삭제한다") void delete(){ when(vehicleMapper.delete(7)).thenReturn(1); assertThat(service.delete(7)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-VEHICLE-017 미입차 방문차량을 취소하고 불가 상태를 거부한다") void cancel(){ when(vehicleMapper.cancelUnenteredVisit("user",2)).thenReturn(1); assertThat(service.cancelUnenteredVisit("user",2)).isEqualTo(1); when(vehicleMapper.cancelUnenteredVisit("user",2)).thenReturn(0); assertThatThrownBy(()->service.cancelUnenteredVisit("user",2)).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-VEHICLE-018 미입차 방문시간을 수정하고 불가 상태를 거부한다") void updateVisitTime(){ VehicleDTO d=visit(2,2); when(vehicleMapper.updateUnenteredVisitTime("user",2,d.getStartDate(),d.getEndDate())).thenReturn(1); assertThat(service.updateUnenteredVisitTime("user",2,d)).isEqualTo(1); when(vehicleMapper.updateUnenteredVisitTime("user",2,d.getStartDate(),d.getEndDate())).thenReturn(0); assertThatThrownBy(()->service.updateUnenteredVisitTime("user",2,d)).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-VEHICLE-019 입차 방문차량을 1~24시간 월 한도 내에서 연장한다") void extendVisit(){ when(vehicleMapper.extendEnteredVisitHours("user",2,1)).thenReturn(1); assertThat(service.extendEnteredVisitHours("user",2,1)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-VEHICLE-020 방문차량 연장은 시간범위·월 한도·차량상태 오류를 거부한다") void extendVisitFailures(){ assertThatThrownBy(()->service.extendEnteredVisitHours("user",2,0)).isInstanceOf(ResponseStatusException.class); assertThatThrownBy(()->service.extendEnteredVisitHours("user",2,25)).isInstanceOf(ResponseStatusException.class); when(vehicleMapper.sumMonthlyRequestedVisitMinutesByLoginId("user")).thenReturn(9000); assertThatThrownBy(()->service.extendEnteredVisitHours("user",2,1)).isInstanceOf(ResponseStatusException.class); when(vehicleMapper.sumMonthlyRequestedVisitMinutesByLoginId("user")).thenReturn(0); assertThatThrownBy(()->service.extendEnteredVisitHours("user",2,1)).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-VEHICLE-021 입주민 일반차량 만기일을 연장한다") void extendNormal(){ LocalDateTime end=LocalDateTime.now().plusDays(10); when(vehicleMapper.extendResidentNormalVehicle("user",2,end)).thenReturn(1); assertThat(service.extendResidentNormalVehicle("user",2,end)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-VEHICLE-022 일반차량 연장은 과거·미존재 차량을 거부한다") void extendNormalFailures(){ assertThatThrownBy(()->service.extendResidentNormalVehicle("user",2,null)).isInstanceOf(ResponseStatusException.class); assertThatThrownBy(()->service.extendResidentNormalVehicle("user",2,LocalDateTime.now().minusDays(1))).isInstanceOf(ResponseStatusException.class); LocalDateTime end=LocalDateTime.now().plusDays(1); assertThatThrownBy(()->service.extendResidentNormalVehicle("user",2,end)).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-VEHICLE-023 차량번호와 기간을 검증해 기본정보를 수정한다") void update(){ VehicleDTO d=adminVehicle(); d.setCarNo("12 가 3456"); when(vehicleMapper.update(d)).thenReturn(1); assertThat(service.update(d)).isEqualTo(1); assertThat(d.getCarNo()).isEqualTo("12가3456"); }
 @Test @DisplayName("UT-BE-VEHICLE-024 차량 수정은 빈 번호와 잘못된 기간을 거부한다") void updateFailures(){ VehicleDTO blankCar=adminVehicle(); blankCar.setCarNo(" "); assertThatThrownBy(()->service.update(blankCar)).isInstanceOf(ResponseStatusException.class); VehicleDTO badDate=adminVehicle(); badDate.setEndDate(badDate.getStartDate()); assertThatThrownBy(()->service.update(badDate)).isInstanceOf(ResponseStatusException.class); }
 private void stubGeneratedInsert(int no){ doAnswer(i->{ VehicleDTO d=i.getArgument(1); d.setVehicleCarNo(no); return 1; }).when(vehicleMapper).insert(anyString(),any()); }
 private VehicleDTO adminVehicle(){ VehicleDTO d=new VehicleDTO(); d.setCarNo("12가3456"); d.setVehicleType("normal"); d.setMemberNo(1); d.setStartDate(LocalDateTime.now().plusHours(2)); d.setEndDate(d.getStartDate().plusDays(30)); return d; }
 private VehicleDTO visit(int afterHours,int durationHours){ VehicleDTO d=new VehicleDTO(); d.setCarNo("12가3456"); d.setStartDate(LocalDateTime.now().plusHours(afterHours)); d.setEndDate(d.getStartDate().plusHours(durationHours)); return d; }
 private VehicleDTO visitMinutes(int afterHours,int minutes){ VehicleDTO d=visit(afterHours,1); d.setEndDate(d.getStartDate().plusMinutes(minutes)); return d; }
}
