package api.vehicle_p; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.http.HttpStatus; import org.springframework.security.core.Authentication; import org.springframework.web.server.ResponseStatusException; import java.time.LocalDateTime; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class VehicleControllerTest { @Mock VehicleService service; @Mock Authentication auth; @InjectMocks VehicleController controller; @BeforeEach void login(){ lenient().when(auth.getName()).thenReturn("user"); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-001 서비스 예외를 상태와 메시지 응답으로 변환한다") void error(){ var r=controller.vehicleRequestError(new ResponseStatusException(HttpStatus.CONFLICT,"중복")); assertThat(r.getStatusCode().value()).isEqualTo(409); assertThat(r.getBody()).containsEntry("message","중복"); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-002 차량 목록을 조회한다") void list(){ List<VehicleDTO>x=List.of(); when(service.listservice()).thenReturn(x); assertThat(controller.list()).isSameAs(x); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-003 조건별 회원 차량을 검색한다") void search(){ List<VehicleDTO>x=List.of(); when(service.search("normal","RESIDENT")).thenReturn(x); assertThat(controller.search("normal","RESIDENT")).isSameAs(x); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-004 입주민 본인 차량을 조회한다") void resident(){ List<VehicleDTO>x=List.of(); when(service.residentList("user")).thenReturn(x); assertThat(controller.residentList(auth)).isSameAs(x); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-005 월 방문 등록·한도·잔여시간을 반환한다") void monthly(){ when(service.getMonthlyRegisteredVisitCount("user")).thenReturn(100); when(service.getMonthlyVisitLimitCount("user")).thenReturn(150); assertThat(controller.monthlyVisitRegistration(auth)).containsEntry("registeredCount",100).containsEntry("limitCount",150).containsEntry("remainingCount",50); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-006 관리자가 차량을 등록한다") void admin(){ VehicleDTO d=new VehicleDTO(); when(service.adminRequest(d)).thenReturn(1); assertThat(controller.adminRequest(d)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-007 입주민이 방문차량을 신청한다") void visit(){ VehicleDTO d=new VehicleDTO(); when(service.residentVisitRequest("user",d)).thenReturn(1); assertThat(controller.residentVisitRequest(auth,d)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-008 미입차 방문차량을 취소한다") void cancel(){ when(service.cancelUnenteredVisit("user",1)).thenReturn(1); assertThat(controller.cancelUnenteredVisit(auth,1)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-009 미입차 방문시간을 수정한다") void time(){ VehicleDTO d=new VehicleDTO(); when(service.updateUnenteredVisitTime("user",1,d)).thenReturn(1); assertThat(controller.updateUnenteredVisitTime(auth,1,d)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-010 입차 방문시간을 연장한다") void extend(){ when(service.extendEnteredVisitHours("user",1,2)).thenReturn(1); assertThat(controller.extendEnteredVisitHours(auth,1,2)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-011 일반차량 만기일을 연장한다") void normal(){ VehicleDTO d=new VehicleDTO(); LocalDateTime end=LocalDateTime.now().plusDays(1); d.setEndDate(end); when(service.extendResidentNormalVehicle("user",1,end)).thenReturn(1); assertThat(controller.extendResidentNormalVehicle(auth,1,d)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-012 차량을 삭제한다") void delete(){ when(service.delete(1)).thenReturn(1); assertThat(controller.deleteVehicle(1)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-VEHICLE-CTRL-013 경로 번호를 DTO에 설정해 차량을 수정한다") void update(){ VehicleDTO d=new VehicleDTO(); when(service.update(d)).thenReturn(1); assertThat(controller.updateVehicle(7,d)).isEqualTo(1); assertThat(d.getVehicleCarNo()).isEqualTo(7); } }
