package api.trash_p;
import api.bill_p.*; import api.cameradata_p.CameraDataMapper; import api.carlog_p.CarLogMapper; import api.inquiry_p.InquiryMapper; import api.notice_p.NoticeMapper; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import java.util.List; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class TrashServiceTest {
 @Mock TrashMapper trashMapper; @Mock CameraDataMapper cameraDataMapper; @Mock CarLogMapper carLogMapper; @Mock NoticeMapper noticeMapper; @Mock InquiryMapper inquiryMapper; @Mock BillMapper billMapper; @InjectMocks TrashService service;
 @Test @DisplayName("UT-BE-TRASH-001 지난 기록 목록을 반환한다") void list(){ List<TrashDTO>x=List.of(new TrashDTO()); when(trashMapper.list("BILL")).thenReturn(x); assertThat(service.list("BILL")).isSameAs(x); }
 @Test @DisplayName("UT-BE-TRASH-002 지난 기록 상세를 반환한다") void detail(){ TrashDTO x=new TrashDTO(); when(trashMapper.detail(1)).thenReturn(x); assertThat(service.detail(1)).isSameAs(x); }
 @Test @DisplayName("UT-BE-TRASH-003 차량번호로 지난 기록을 검색한다") void search(){ List<TrashDTO>x=List.of(); when(trashMapper.searchByCarNo("1234")).thenReturn(x); assertThat(service.searchByCarNo("1234")).isSameAs(x); }
 @Test @DisplayName("UT-BE-TRASH-004 카메라·카로그·알림·정산 기록을 유형별 복원한다") void restoreTypes(){ for(String type:List.of("CAMERA_DATA","CAR_LOG","NOTICE","BILL")){ TrashDTO t=trash(1,9,type); when(trashMapper.detail(1)).thenReturn(t); if(type.equals("CAMERA_DATA"))when(trashMapper.restoreCameraData(1)).thenReturn(1); if(type.equals("CAR_LOG"))when(trashMapper.restoreCarLog(1)).thenReturn(1); if(type.equals("NOTICE"))when(trashMapper.restoreNotice(1)).thenReturn(1); if(type.equals("BILL"))when(trashMapper.restoreBill(1)).thenReturn(1); when(trashMapper.deleteTrash(1)).thenReturn(1); assertThat(service.restore(1).getRestoredNo()).isEqualTo(9); reset(trashMapper); } }
 @Test @DisplayName("UT-BE-TRASH-005 문의와 재문의 묶음을 순서대로 복원한다") void restoreInquiry(){ TrashDTO t=trash(3,9,"INQUIRY"); when(trashMapper.detail(3)).thenReturn(t); when(trashMapper.findInquiryTrashNosForRestore(3)).thenReturn(List.of(3,4)); when(trashMapper.restoreInquiry(anyInt())).thenReturn(1); when(trashMapper.deleteTrash(anyInt())).thenReturn(1); assertThat(service.restore(3).getSuccess()).isTrue(); verify(trashMapper).restoreInquiry(3); verify(trashMapper).restoreInquiry(4); }
 @Test @DisplayName("UT-BE-TRASH-006 복원은 미존재·미지원 유형·복원 및 휴지통 삭제 실패를 거부한다") void restoreFailures(){ assertThatThrownBy(()->service.restore(1)).isInstanceOf(IllegalArgumentException.class); TrashDTO t=trash(1,9,"BAD"); when(trashMapper.detail(1)).thenReturn(t); assertThatThrownBy(()->service.restore(1)).isInstanceOf(IllegalArgumentException.class); t.setDataType("CAMERA_DATA"); when(trashMapper.restoreCameraData(1)).thenReturn(0); assertThatThrownBy(()->service.restore(1)).isInstanceOf(IllegalStateException.class); when(trashMapper.restoreCameraData(1)).thenReturn(1); when(trashMapper.deleteTrash(1)).thenReturn(0); assertThatThrownBy(()->service.restore(1)).isInstanceOf(IllegalStateException.class); }
 @Test @DisplayName("UT-BE-TRASH-007 카메라 기록을 저장한 뒤 원본을 삭제한다") void moveCamera(){ when(trashMapper.saveCameraData(1,"M")).thenReturn(1); when(cameraDataMapper.delete(1)).thenReturn(1); service.moveCameraData(1,"M"); }
 @Test @DisplayName("UT-BE-TRASH-008 카메라 기록 이동의 저장·삭제 실패를 거부한다") void moveCameraFailures(){ assertThatThrownBy(()->service.moveCameraData(1,"M")).isInstanceOf(IllegalArgumentException.class); when(trashMapper.saveCameraData(1,"M")).thenReturn(1); assertThatThrownBy(()->service.moveCameraData(1,"M")).isInstanceOf(IllegalStateException.class); }
 @Test @DisplayName("UT-BE-TRASH-009 카로그 기록을 저장한 뒤 원본을 삭제한다") void moveCarLog(){ when(trashMapper.saveCarLog(1,"M")).thenReturn(1); when(carLogMapper.delete(1)).thenReturn(1); service.moveCarLog(1,"M"); }
 @Test @DisplayName("UT-BE-TRASH-010 카로그 기록 이동의 저장·삭제 실패를 거부한다") void moveCarLogFailures(){ assertThatThrownBy(()->service.moveCarLog(1,"M")).isInstanceOf(IllegalArgumentException.class); when(trashMapper.saveCarLog(1,"M")).thenReturn(1); assertThatThrownBy(()->service.moveCarLog(1,"M")).isInstanceOf(IllegalStateException.class); }
 @Test @DisplayName("UT-BE-TRASH-011 알림 기록을 저장한 뒤 원본을 삭제한다") void moveNotice(){ when(trashMapper.saveNotice(1,"M")).thenReturn(1); when(noticeMapper.delete(1)).thenReturn(1); service.moveNotice(1,"M"); }
 @Test @DisplayName("UT-BE-TRASH-012 알림 기록 이동의 저장·삭제 실패를 거부한다") void moveNoticeFailures(){ assertThatThrownBy(()->service.moveNotice(1,"M")).isInstanceOf(IllegalArgumentException.class); when(trashMapper.saveNotice(1,"M")).thenReturn(1); assertThatThrownBy(()->service.moveNotice(1,"M")).isInstanceOf(IllegalStateException.class); }
 @Test @DisplayName("UT-BE-TRASH-013 문의 기록을 저장한 뒤 원본을 삭제한다") void moveInquiry(){ when(trashMapper.saveInquiry(1,"M")).thenReturn(1); when(inquiryMapper.delete(1)).thenReturn(1); service.moveInquiry(1,"M"); }
 @Test @DisplayName("UT-BE-TRASH-014 문의 기록 이동의 저장·삭제 실패를 거부한다") void moveInquiryFailures(){ assertThatThrownBy(()->service.moveInquiry(1,"M")).isInstanceOf(IllegalArgumentException.class); when(trashMapper.saveInquiry(1,"M")).thenReturn(1); assertThatThrownBy(()->service.moveInquiry(1,"M")).isInstanceOf(IllegalStateException.class); }
 @Test @DisplayName("UT-BE-TRASH-015 결제 완료 정산서를 저장한 뒤 원본을 삭제한다") void moveBill(){ BillDTO b=new BillDTO(); b.setBillStatus("PAID"); when(billMapper.detail(any())).thenReturn(b); when(trashMapper.saveBill(1,"M")).thenReturn(1); when(billMapper.delete(1)).thenReturn(1); service.moveBill(1,"M"); }
 @Test @DisplayName("UT-BE-TRASH-016 정산 이동은 미결제·저장 실패·삭제 실패를 거부한다") void moveBillFailures(){ assertThatThrownBy(()->service.moveBill(1,"M")).isInstanceOf(IllegalArgumentException.class); BillDTO b=new BillDTO(); b.setBillStatus("PAID"); when(billMapper.detail(any())).thenReturn(b); assertThatThrownBy(()->service.moveBill(1,"M")).isInstanceOf(IllegalStateException.class); when(trashMapper.saveBill(1,"M")).thenReturn(1); assertThatThrownBy(()->service.moveBill(1,"M")).isInstanceOf(IllegalStateException.class); }
 private TrashDTO trash(int no,int original,String type){ TrashDTO d=new TrashDTO(); d.setTrashNo(no); d.setOriginalNo(original); d.setDataType(type); return d; }
}
