package api.member_p;
import api.a_security_config.VerificationService; import api.apartmentunit_p.ApartmentUnitDTO; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.http.HttpStatus; import org.springframework.security.authentication.UsernamePasswordAuthenticationToken; import org.springframework.security.core.Authentication; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.web.server.ResponseStatusException; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class MemberControllerTest {
 @Mock MemberService service; @Mock VerificationService verification; @InjectMocks MemberController controller;
 @Test @DisplayName("UT-BE-MEMBER-CTRL-001 외부 가입은 입주민 승인대기로 고정한다") void publicSignup(){ MemberDTO d=new MemberDTO(); controller.signup(d,null); assertThat(d.getRole()).isEqualTo("RESIDENT"); assertThat(d.getMemStatus()).isEqualTo("PENDING"); verify(service).signup(d); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-002 관리자 가입은 입력 역할과 상태를 유지한다") void adminSignup(){ MemberDTO d=new MemberDTO(); d.setRole("ADMIN"); d.setMemStatus("ACTIVE"); controller.signup(d,auth("admin","ADMIN")); assertThat(d.getRole()).isEqualTo("ADMIN"); verify(service).signup(d); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-003 전화 인증번호를 발송한다") void sendPhone(){ var r=new MemberDTO.VerificationCodeRequest("010","123"); controller.sendPhoneCode(r); verify(verification).sendSignupPhoneCode("010"); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-004 전화 인증번호를 확인한다") void verifyPhone(){ var r=new MemberDTO.VerificationCodeRequest("010","123"); controller.verifyPhoneCode(r); verify(verification).verifySignupPhoneCode("010","123"); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-005 이메일 인증번호를 발송한다") void sendEmail(){ var r=new MemberDTO.VerificationCodeRequest("a@b.com","123"); controller.sendEmailCode(r); verify(verification).sendSignupEmailCode("a@b.com"); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-006 이메일 인증번호를 확인한다") void verifyEmail(){ var r=new MemberDTO.VerificationCodeRequest("a@b.com","123"); controller.verifyEmailCode(r); verify(verification).verifySignupEmailCode("a@b.com","123"); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-007 계정복구 인증번호를 발송한다") void recoverySend(){ var r=recovery(); controller.sendAccountRecoveryCode(r); verify(service).sendAccountRecoveryCode(r); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-008 인증 후 로그인 아이디를 반환한다") void findId(){ var r=recovery(); var x=new MemberDTO.AccountRecoveryResponse("user"); when(service.findAccountLoginId(r)).thenReturn(x); assertThat(controller.findAccountLoginId(r)).isSameAs(x); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-009 계정 비밀번호를 재설정한다") void resetPassword(){ var r=recovery(); controller.resetAccountPassword(r); verify(service).resetAccountPassword(r); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-010 로그인 아이디 중복 여부를 조회한다") void checkId(){ when(service.checkLoginId("user")).thenReturn(true); assertThat(controller.checkLoginId("user")).isTrue(); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-011 가입 가능한 세대를 조회한다") void units(){ List<ApartmentUnitDTO>x=List.of(); when(service.availableSignupUnits()).thenReturn(x); assertThat(controller.availableSignupUnits()).isSameAs(x); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-012 경로 회원번호와 관리자 ID로 회원을 수정한다") void update(){ MemberDTO d=new MemberDTO(); controller.update(7,d,auth("admin","ADMIN")); assertThat(d.getMemberNo()).isEqualTo(7); verify(service).update(d,"admin"); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-013 선택 회원을 승인한다") void approve(){ controller.approvePendingMembers(List.of(1,2)); verify(service).approvePendingMembers(List.of(1,2)); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-014 회원 목록을 조회한다") void list(){ List<MemberDTO>x=List.of(); when(service.list()).thenReturn(x); assertThat(controller.list()).isSameAs(x); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-015 회원 상세를 조회한다") void detail(){ MemberDTO x=new MemberDTO(); when(service.detail(1)).thenReturn(x); assertThat(controller.detail(1)).isSameAs(x); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-016 조건별 회원을 검색한다") void search(){ List<MemberDTO>x=List.of(); when(service.search("name","kim",101,101)).thenReturn(x); assertThat(controller.search("name","kim",101,101)).isSameAs(x); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-017 선택 전출 회원을 복원한다") void restoreMany(){ when(service.restoreWithdrawnMembers(List.of(1,2))).thenReturn(2); assertThat(controller.restoreWithdrawnMembers(List.of(1,2))).isEqualTo(2); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-018 선택 전출 회원을 확정한다") void deleteMany(){ when(service.permanentlyDeleteWithdrawnMembers(List.of(1,2))).thenReturn(2); assertThat(controller.permanentlyDeleteWithdrawnMembers(List.of(1,2))).isEqualTo(2); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-019 관리자가 회원을 전출 신청 처리한다") void delete(){ controller.delete(1,auth("admin","ADMIN")); verify(service).delete(1,"admin"); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-020 전출 회원 한 명을 복원한다") void restoreOne(){ controller.restoreWithdrawnMember(1); verify(service).restoreWithdrawnMember(1); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-021 전출 회원 한 명을 확정한다") void confirmOne(){ controller.confirmWithdrawnMember(1); verify(service).confirmWithdrawnMember(1); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-022 입주민 마이페이지를 조회한다") void mypage(){ MemberDTO x=new MemberDTO(); when(service.residentMypage("user")).thenReturn(x); assertThat(controller.residentMypage(auth("user","RESIDENT"))).isSameAs(x); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-023 입주민 대시보드를 조회한다") void dashboard(){ MemberDTO.ResidentDashboard x=new MemberDTO.ResidentDashboard(); when(service.residentDashboard("user")).thenReturn(x); assertThat(controller.residentDashboard(auth("user","RESIDENT"))).isSameAs(x); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-024 로그인 ID를 DTO에 고정해 마이페이지를 수정한다") void editMypage(){ MemberDTO d=new MemberDTO(); controller.residentMypageEdit(auth("user","RESIDENT"),d); assertThat(d.getLoginId()).isEqualTo("user"); verify(service).residentMypageEdit(d); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-025 인증 입주민에게 보안문자를 발급한다") void challenge(){ Map<String,String>x=Map.of("id","1"); when(service.issueSecurityChallenge()).thenReturn(x); assertThat(controller.issueSecurityChallenge(auth("user","RESIDENT"))).isSameAs(x); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-026 미인증 보안문자 발급을 거부한다") void challengeUnauthorized(){ assertThatThrownBy(()->controller.issueSecurityChallenge(null)).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-027 탈퇴 사전 확인 성공은 204를 반환한다") void verifyWithdrawal(){ assertThat(controller.verifyResidentWithdrawal(auth("user","RESIDENT"),security()).getStatusCode().value()).isEqualTo(204); verify(service).verifyResidentWithdrawal("user","current","id","answer"); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-028 탈퇴 사전 확인 실패 상태와 메시지를 반환한다") void verifyWithdrawalFailure(){ doThrow(new ResponseStatusException(HttpStatus.UNAUTHORIZED,"불일치")).when(service).verifyResidentWithdrawal(any(),any(),any(),any()); var response=controller.verifyResidentWithdrawal(auth("user","RESIDENT"),security()); assertThat(response.getStatusCode().value()).isEqualTo(401); assertThat(response.getBody()).containsEntry("message","불일치"); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-029 입주민 탈퇴 성공은 204를 반환한다") void residentDelete(){ assertThat(controller.residentDelete(auth("user","RESIDENT"),security()).getStatusCode().value()).isEqualTo(204); verify(service).residentDelete("user","current","id","answer"); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-030 입주민 탈퇴 실패 상태를 반환한다") void residentDeleteFailure(){ doThrow(new ResponseStatusException(HttpStatus.BAD_REQUEST)).when(service).residentDelete(any(),any(),any(),any()); assertThat(controller.residentDelete(auth("user","RESIDENT"),security()).getStatusCode().value()).isEqualTo(400); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-031 비밀번호 변경 성공은 204를 반환한다") void changePassword(){ assertThat(controller.changeResidentPassword(auth("user","RESIDENT"),security()).getStatusCode().value()).isEqualTo(204); verify(service).changeResidentPassword("user","current","new","id","answer"); }
 @Test @DisplayName("UT-BE-MEMBER-CTRL-032 비밀번호 변경 실패 상태를 반환한다") void changePasswordFailure(){ doThrow(new ResponseStatusException(HttpStatus.BAD_REQUEST,"실패")).when(service).changeResidentPassword(any(),any(),any(),any(),any()); assertThat(controller.changeResidentPassword(auth("user","RESIDENT"),security()).getStatusCode().value()).isEqualTo(400); }
 private Authentication auth(String id,String role){ return new UsernamePasswordAuthenticationToken(id,"",List.of(new SimpleGrantedAuthority(role))); }
 private MemberDTO.AccountRecoveryRequest recovery(){ return new MemberDTO.AccountRecoveryRequest("FIND_ID","PHONE","010","김",101,101,null,"123",null); }
 private MemberDTO.ResidentSecurityRequest security(){ return new MemberDTO.ResidentSecurityRequest("current","new","id","answer"); }
}
