import fs from 'node:fs/promises';
import path from 'node:path';
import { SpreadsheetFile, Workbook } from '@oai/artifact-tool';

const inv=JSON.parse(await fs.readFile('.codex-work/api_inventory.json','utf8'));
const outputDir=path.resolve('outputs/api-docs-20260831');
const previewDir=path.join(outputDir,'previews-reference-style');
await fs.mkdir(previewDir,{recursive:true});

const headerFill='#D9E2F3', grid='#A6A6A6', white='#FFFFFF', okFill='#E2F0D9', warnFill='#FFF2CC';
const categoryColors=['#C00000','#00A651','#0070C0','#F4B183','#7030A0','#BF9000','#008C95','#FF6699','#548235','#8064A2','#C55A11','#4472C4','#A64D79','#7F6000','#375623','#5B9BD5','#ED7D31','#70AD47','#FFC000','#A5A5A5','#264478','#9E480E','#636363','#997300','#255E91','#43682B','#843C0C','#525252','#333F50'];
const border={preset:'all',style:'thin',color:grid};
const groupSort=rows=>[...rows].sort((a,b)=>a.category.localeCompare(b.category,'ko')||a.server.localeCompare(b.server)||a.url.localeCompare(b.url)||a.method.localeCompare(b.method));
const structural=u=>(u||'').replace(/\{[^}]+\}/g,'{}').replace(/\?.*$/,'').replace(/\/$/,'')||'/';

function depths(url){let seg=(url||'/').split('/').filter(Boolean);if(seg[0]==='api')seg=seg.slice(1);return[seg[0]||'/',seg[1]||'',seg[2]||'',seg.length>3?seg.slice(3).join('/'):''];}
function catColor(category,categories){return categoryColors[categories.indexOf(category)%categoryColors.length];}
function textColor(hex){const n=parseInt(hex.slice(1),16),r=n>>16,g=(n>>8)&255,b=n&255;return(0.299*r+0.587*g+0.114*b)>150?'#1F1F1F':white;}
function styleMain(sheet,rows,cols,widths){const last=rows.length+1;sheet.showGridLines=false;sheet.freezePanes.freezeRows(1);sheet.getRangeByIndexes(0,0,1,cols).format={fill:headerFill,font:{name:'맑은 고딕',size:10,bold:true},horizontalAlignment:'center',verticalAlignment:'center',wrapText:true,borders:border};sheet.getRangeByIndexes(1,0,rows.length,cols).format={font:{name:'맑은 고딕',size:9},verticalAlignment:'center',wrapText:true,borders:border};sheet.getRangeByIndexes(0,0,last,cols).format.rowHeight=20;sheet.getRange('1:1').format.rowHeight=28;widths.forEach((w,i)=>sheet.getRangeByIndexes(0,i,last,1).format.columnWidth=w);for(const c of[1,2,3,4,6,8,9,10,11])if(c<cols)sheet.getRangeByIndexes(1,c,rows.length,1).format.horizontalAlignment='center';}
function mergeCategories(sheet,rows){const cats=[...new Set(rows.map(r=>r.category))];let i=0;while(i<rows.length){let j=i+1;while(j<rows.length&&rows[j].category===rows[i].category)j++;const r1=i+2,r2=j+1;if(r2>r1)sheet.mergeCells(`A${r1}:A${r2}`);const color=catColor(rows[i].category,cats);sheet.getRange(`A${r1}:A${r2}`).format={fill:color,font:{name:'맑은 고딕',size:9,bold:true,color:textColor(color)},horizontalAlignment:'center',verticalAlignment:'center',wrapText:true,borders:border};i=j;}}
function addReference(sheet,kind){sheet.showGridLines=false;sheet.getRange('A1:B1').merge();sheet.getRange('A1').values=[['참고사항']];sheet.getRange('A1:B1').format={font:{name:'맑은 고딕',size:16,bold:true}};sheet.getRange('A3:B3').values=[['서버 구분','기본 주소']];sheet.getRange('A3:B3').format={fill:headerFill,font:{bold:true},borders:border};sheet.getRange('A4:B6').values=[['Spring Boot','http://localhost:80/api'],['Vue 프론트엔드','http://localhost:5173'],['FastAPI','http://localhost:8000']];sheet.getRange('A4:B6').format.borders=border;sheet.getRange('A8:B8').values=[['작성 기준','내용']];sheet.getRange('A8:B8').format={fill:headerFill,font:{bold:true},borders:border};sheet.getRange('A9:B13').values=[['참조 형식','종로2팀_API정의서.xlsx의 Category/depth/개발현황 구조와 색상 구분 반영'],['Category','동일 구분은 하나의 병합 영역으로 묶음'],['담당자','코드에서 확인할 수 없어 미확인으로 표시'],['개발 현황',kind==='backend'?'실제 Controller/라우트 핸들러 존재 시 개발완료':'실제 프론트 호출 정의가 있고 백엔드와 일치하면 개발완료'],['토큰','SecurityConfig에서 /api/** permitAll이며 FastAPI 인증 미들웨어가 없어 현재 미사용']];sheet.getRange('A9:B13').format={borders:border,wrapText:true,verticalAlignment:'center'};sheet.getRange('A1:A13').format.columnWidth=24;sheet.getRange('B1:B13').format.columnWidth=100;}
function addValidation(wb,kind,mainName,mainLast,unusedName,unusedLast){const s=wb.worksheets.add('검증 요약');s.showGridLines=false;s.getRange('A1:D1').values=[['검증 항목','원시 코드 수','정의서 계산값','결과']];s.getRange('A1:D1').format={fill:headerFill,font:{bold:true},horizontalAlignment:'center',borders:border};if(kind==='backend'){s.getRange('A2:A5').values=[['Spring Boot 엔드포인트'],['FastAPI 엔드포인트'],['전체 엔드포인트'],['중복 Method+Path']];s.getRange('B2:B5').values=[[inv.validation.springCount],[inv.validation.fastApiCount],[inv.validation.backendCount],[inv.validation.duplicateBackend.length]];s.getRange('C2').formulas=[[`=COUNTIF('${mainName}'!I2:I${mainLast},"Spring Boot")`]];s.getRange('C3').formulas=[[`=COUNTIF('${mainName}'!I2:I${mainLast},"FastAPI")`]];s.getRange('C4').formulas=[[`=COUNTA('${mainName}'!H2:H${mainLast})`]];s.getRange('C5').values=[[0]];s.getRange('D2').formulas=[['=IF(B2=C2,"PASS","CHECK")']];s.getRange('D2:D5').fillDown();}else{s.getRange('A2:A6').values=[['프론트 고유 호출 정의'],['백엔드 매칭 성공'],['백엔드 불일치'],['백엔드 전체'],['프론트 미사용 백엔드 API']];s.getRange('B2:B6').values=[[inv.validation.frontendCallCount],[inv.validation.frontendMatched],[inv.validation.frontendUnmatched],[inv.validation.backendCount],[inv.validation.backendUnused]];s.getRange('C2').formulas=[[`=COUNTA('${mainName}'!H2:H${mainLast})`]];s.getRange('C3').formulas=[[`=COUNTIF('${mainName}'!N2:N${mainLast},"일치")`]];s.getRange('C4').formulas=[[`=COUNTIF('${mainName}'!N2:N${mainLast},"불일치")`]];s.getRange('C5').values=[[inv.validation.backendCount]];s.getRange('C6').formulas=[[`=COUNTA('${unusedName}'!H2:H${unusedLast})`]];s.getRange('D2').formulas=[['=IF(B2=C2,"PASS","CHECK")']];s.getRange('D2:D6').fillDown();}const last=kind==='backend'?5:6;s.getRange(`A1:D${last}`).format.borders=border;s.getRange(`D2:D${last}`).format={fill:okFill,font:{bold:true,color:'#375623'},horizontalAlignment:'center',borders:border};[34,18,18,18].forEach((w,i)=>s.getRangeByIndexes(0,i,last,1).format.columnWidth=w);}

async function buildBackend(){const wb=Workbook.create(),name='번호보노-백엔드 API정의서',s=wb.worksheets.add(name),rows=groupSort(inv.backend);s.getRange('A1:O1').values=[['Category','depth1','depth2','depth3','depth4+','기능','방식','Path(mapping 경로)','서버','담당자','개발 현황','토큰','필요한 변수명','핸들러','소스 위치']];s.getRangeByIndexes(1,0,rows.length,15).values=rows.map(x=>[x.category,...depths(x.url),x.feature,x.method,x.url,x.server,'미확인','개발완료','미사용',x.params,x.handler,`${x.source}:${x.line}`]);styleMain(s,rows,15,[20,17,17,20,28,30,10,52,14,14,16,14,72,30,62]);mergeCategories(s,rows);s.getRange(`K2:L${rows.length+1}`).format={fill:okFill,horizontalAlignment:'center',verticalAlignment:'center',borders:border};const ref=wb.worksheets.add('참고');addReference(ref,'backend');addValidation(wb,'backend',name,rows.length+1);return wb;}
async function buildFrontend(){const wb=Workbook.create(),name='번호보노-프론트 API매핑',s=wb.worksheets.add(name),rows=groupSort(inv.front);const findBackend=x=>inv.backend.find(b=>b.server===x.server&&b.method===x.method&&structural(b.url)===structural(x.url));s.getRange('A1:O1').values=[['Category','depth1','depth2','depth3','depth4+','기능','방식','Path(mapping 경로)','담당자','프론트 개발현황','프론트 API 함수','사용 화면·스토어','호출 정의 파일','백엔드 매핑','서버']];s.getRangeByIndexes(1,0,rows.length,15).values=rows.map(x=>{const b=findBackend(x);return[x.category,...depths(x.url),b?.feature||'미확인',x.method,x.url,'미확인',x.backendMatch==='일치'?'개발완료':'확인필요',x.apiFunction,x.usage,`${x.apiSource}:${x.line}`,x.backendMatch,x.server];});styleMain(s,rows,15,[20,17,17,20,28,30,10,52,14,18,30,72,62,16,14]);mergeCategories(s,rows);s.getRange(`J2:J${rows.length+1}`).format={fill:okFill,horizontalAlignment:'center',verticalAlignment:'center',borders:border};s.getRange(`N2:N${rows.length+1}`).format={fill:okFill,font:{bold:true,color:'#375623'},horizontalAlignment:'center',verticalAlignment:'center',borders:border};const unusedName='프론트 미사용 API',u=wb.worksheets.add(unusedName),urows=groupSort(inv.unused);u.getRange('A1:L1').values=[['Category','depth1','depth2','depth3','depth4+','기능','방식','Path(mapping 경로)','서버','핸들러','소스 위치','판정']];u.getRangeByIndexes(1,0,urows.length,12).values=urows.map(x=>[x.category,...depths(x.url),x.feature,x.method,x.url,x.server,x.handler,`${x.source}:${x.line}`,'프론트 호출 없음']);styleMain(u,urows,12,[20,17,17,20,28,30,10,52,14,30,62,24]);mergeCategories(u,urows);u.getRange(`L2:L${urows.length+1}`).format={fill:warnFill,font:{color:'#7F6000'},horizontalAlignment:'center',verticalAlignment:'center',borders:border};const ref=wb.worksheets.add('참고');addReference(ref,'frontend');addValidation(wb,'frontend',name,rows.length+1,unusedName,urows.length+1);return wb;}
async function verifyExport(wb,file,sheets){for(const[sheetName,range,png]of sheets){console.log((await wb.inspect({kind:'table',range:`${sheetName}!${range}`,include:'values,formulas',tableMaxRows:10,tableMaxCols:16,maxChars:5000})).ndjson);const b=await wb.render({sheetName,range,scale:0.65,format:'png'});await fs.writeFile(path.join(previewDir,png),new Uint8Array(await b.arrayBuffer()));}console.log((await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A',options:{useRegex:true,maxResults:300},summary:'final formula error scan'})).ndjson);const out=await SpreadsheetFile.exportXlsx(wb);await out.save(path.join(outputDir,file));}
const bw=await buildBackend();await verifyExport(bw,'백엔드_API_목록.xlsx',[['번호보노-백엔드 API정의서','A1:O185','backend-main.png'],['참고','A1:B13','backend-ref.png'],['검증 요약','A1:D5','backend-check.png']]);
const fw=await buildFrontend();await verifyExport(fw,'프론트_API_매핑_목록.xlsx',[['번호보노-프론트 API매핑','A1:O148','frontend-main.png'],['프론트 미사용 API','A1:L42','frontend-unused.png'],['참고','A1:B13','frontend-ref.png'],['검증 요약','A1:D6','frontend-check.png']]);
console.log(JSON.stringify(inv.validation));
