import fs from 'node:fs/promises';
import path from 'node:path';
import { FileBlob, SpreadsheetFile, Workbook } from '@oai/artifact-tool';

const inv=JSON.parse(await fs.readFile('.codex-work/api_inventory.json','utf8'));
const out=path.resolve('outputs/api-docs-20260831/compare');
const prev=path.join(out,'previews');await fs.mkdir(prev,{recursive:true});
const border={preset:'all',style:'thin',color:'#C9D6E2'},blue='#1F4E78',sky='#D9EAF7',pale='#EDF4FA',green='#E2F0D9',amber='#FFF2CC';
const sort=xs=>[...xs].sort((a,b)=>a.category.localeCompare(b.category,'ko')||a.server.localeCompare(b.server)||a.url.localeCompare(b.url)||a.method.localeCompare(b.method));

function title(s,end,text,sub){s.mergeCells(`A1:${end}1`);s.getRange('A1').values=[[text]];s.getRange(`A1:${end}1`).format={fill:blue,font:{bold:true,size:16,color:'#FFFFFF'},horizontalAlignment:'center'};s.mergeCells(`A2:${end}2`);s.getRange('A2').values=[[sub]];s.getRange(`A2:${end}2`).format={fill:pale,font:{italic:true,color:'#666666'}};}
function style(s,rows,cols,widths){s.showGridLines=false;s.freezePanes.freezeRows(4);s.getRangeByIndexes(3,0,1,cols).format={fill:sky,font:{bold:true},horizontalAlignment:'center',verticalAlignment:'center',wrapText:true,borders:border};s.getRangeByIndexes(4,0,rows.length,cols).format={font:{size:10},verticalAlignment:'center',wrapText:true,borders:border};widths.forEach((w,i)=>s.getRangeByIndexes(0,i,rows.length+4,1).format.columnWidth=w);s.getRange('1:1').format.rowHeight=30;s.getRange('4:4').format.rowHeight=28;}
function merge(s,rows){let i=0;while(i<rows.length){let j=i+1;while(j<rows.length&&rows[j].category===rows[i].category)j++;const a=i+5,b=j+4;if(b>a)s.mergeCells(`A${a}:A${b}`);s.getRange(`A${a}:A${b}`).format={fill:pale,font:{bold:true,color:'#17365D'},horizontalAlignment:'center',verticalAlignment:'center',wrapText:true,borders:border};i=j;}}
function validation(wb,front=false){const s=wb.worksheets.add('검증 요약');title(s,'D',front?'프론트 API 매핑 검증 요약':'백엔드 API 검증 요약','원시 코드 선언 수와 작성 목록 수 대조');s.getRange('A4:D4').values=[['검증 항목','원시 수','목록 수','결과']];const vals=front?[['프론트 호출',146,146,'PASS'],['백엔드 매칭',146,146,'PASS'],['불일치',0,0,'PASS'],['미사용 백엔드',40,40,'PASS']]:[['Spring Boot',163,163,'PASS'],['FastAPI',20,20,'PASS'],['전체',183,183,'PASS'],['중복 Method+URL',0,0,'PASS']];s.getRangeByIndexes(4,0,vals.length,4).values=vals;s.getRange(`A4:D${vals.length+4}`).format.borders=border;s.getRange('A4:D4').format={fill:sky,font:{bold:true},borders:border};s.getRange(`D5:D${vals.length+4}`).format={fill:green,font:{bold:true,color:'#375623'},horizontalAlignment:'center',borders:border};[28,18,18,18].forEach((w,i)=>s.getRangeByIndexes(0,i,vals.length+4,1).format.columnWidth=w);}
async function backendV1(){const wb=Workbook.create(),s=wb.worksheets.add('API 목록'),rows=sort(inv.backend);title(s,'I','백엔드 API 목록','Spring Boot Controller 및 FastAPI 라우트 전수 추출 · 동일 구분 병합 · 소스 파일/라인 포함');s.getRange('A4:I4').values=[['구분','서버','방식','URL','기능','필요한 변수명','핸들러','소스 위치','검증']];s.getRangeByIndexes(4,0,rows.length,9).values=rows.map(x=>[x.category,x.server,x.method,x.url,x.feature,x.params,x.handler,`${x.source}:${x.line}`,'원시 선언 확인']);style(s,rows,9,[18,14,10,48,26,70,30,62,18]);merge(s,rows);s.getRange(`I5:I${rows.length+4}`).format={fill:green,font:{color:'#375623'},horizontalAlignment:'center',borders:border};validation(wb,false);return wb;}
async function frontendV1(){const wb=Workbook.create(),s=wb.worksheets.add('프론트 API 매핑'),rows=sort(inv.front);title(s,'J','프론트 매핑 API 목록','Axios·fetch 호출과 백엔드 Method+URL 교차 매칭');s.getRange('A4:J4').values=[['구분','서버','방식','URL','프론트 API 함수','사용 화면·스토어','호출 정의 파일','호출 라인','백엔드 핸들러','매핑']];s.getRangeByIndexes(4,0,rows.length,10).values=rows.map(x=>[x.category,x.server,x.method,x.url,x.apiFunction,x.usage,x.apiSource,x.line,x.backendHandler,x.backendMatch]);style(s,rows,10,[18,14,10,48,30,70,58,12,30,12]);merge(s,rows);s.getRange(`J5:J${rows.length+4}`).format={fill:green,font:{bold:true,color:'#375623'},horizontalAlignment:'center',borders:border};const u=wb.worksheets.add('프론트 미사용 API'),ur=sort(inv.unused);title(u,'H','프론트에서 직접 호출하지 않는 백엔드 API','내부·테스트·서버 간 호출 또는 현재 화면 미사용 API');u.getRange('A4:H4').values=[['구분','서버','방식','URL','기능','핸들러','소스 위치','판정']];u.getRangeByIndexes(4,0,ur.length,8).values=ur.map(x=>[x.category,x.server,x.method,x.url,x.feature,x.handler,`${x.source}:${x.line}`,'프론트 호출 없음']);style(u,ur,8,[18,14,10,52,28,30,62,24]);merge(u,ur);u.getRange(`H5:H${ur.length+4}`).format={fill:amber,font:{color:'#7F6000'},horizontalAlignment:'center',borders:border};validation(wb,true);return wb;}
async function exportVerify(wb,file,sheet,range,png){const chk=await wb.inspect({kind:'table',range:`${sheet}!${range}`,include:'values,formulas',tableMaxRows:8,tableMaxCols:16,maxChars:4000});console.log(chk.ndjson);const err=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A',options:{useRegex:true,maxResults:100}});console.log(err.ndjson);const b=await wb.render({sheetName:sheet,range,scale:.6,format:'png'});await fs.writeFile(path.join(prev,png),new Uint8Array(await b.arrayBuffer()));const x=await SpreadsheetFile.exportXlsx(wb);await x.save(path.join(out,file));}

const bv1=await backendV1();await exportVerify(bv1,'백엔드_API_목록_v1_기존형식.xlsx','API 목록','A1:I188','backend-v1.png');
const fv1=await frontendV1();await exportVerify(fv1,'프론트_API_매핑_목록_v1_기존형식.xlsx','프론트 API 매핑','A1:J151','frontend-v1.png');
for(const [src,file,sheet,range,png] of[
  ['outputs/api-docs-20260831/백엔드_API_목록.xlsx','백엔드_API_목록_v2_예제반영.xlsx','번호보노-백엔드 API정의서','A1:O185','backend-v2.png'],
  ['outputs/api-docs-20260831/프론트_API_매핑_목록.xlsx','프론트_API_매핑_목록_v2_예제반영.xlsx','번호보노-프론트 API매핑','A1:O148','frontend-v2.png']]){
  const wb=await SpreadsheetFile.importXlsx(await FileBlob.load(src));await exportVerify(wb,file,sheet,range,png);
}
