package api.robot_p;
import api.parking_space_p.ParkingSpaceService; import api.robot_log_p.RobotLogService; import api.robot_task_p.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import java.math.BigDecimal; import java.time.OffsetDateTime; import java.util.List; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class RobotServiceTest {
 @Mock RobotMapper robotMapper; @Mock RobotTaskMapper robotTaskMapper; @Mock RobotTaskService robotTaskService; @Mock ParkingSpaceService parkingSpaceService; @Mock RobotLogService robotLogService; @InjectMocks RobotService service;
 @Test @DisplayName("UT-BE-ROBOT-001 전체 로봇과 점검 경과일을 조회한다") void list(){ RobotDTO d=new RobotDTO(); d.setLastMaintenanceAt(OffsetDateTime.now().minusDays(3)); when(robotMapper.list()).thenReturn(List.of(d)); assertThat(service.list()).containsExactly(d); assertThat(d.getDaysSinceMaintenance()).isBetween(2,3); }
 @Test @DisplayName("UT-BE-ROBOT-002 로봇 상세와 점검 경과일을 조회한다") void detail(){ RobotDTO d=new RobotDTO(); when(robotMapper.detail(1)).thenReturn(d); assertThat(service.detail(1)).isSameAs(d); assertThat(service.detail(2)).isNull(); }
 @Test @DisplayName("UT-BE-ROBOT-003 같은 세트 로봇을 조회한다") void bySet(){ List<RobotDTO>x=List.of(new RobotDTO()); when(robotMapper.findBySetNo(2)).thenReturn(x); assertThat(service.findBySetNo(2)).isSameAs(x); }
 @Test @DisplayName("UT-BE-ROBOT-004 사용 가능한 세트를 조회한다") void availableSet(){ when(robotMapper.findAvailableSetNo(1)).thenReturn(2); assertThat(service.findAvailableSetNo(1)).isEqualTo(2); }
 @Test @DisplayName("UT-BE-ROBOT-005 로봇 세트 작업을 시작한다") void startSet(){ when(robotMapper.startSet(2)).thenReturn(2); assertThat(service.startSet(2)).isEqualTo(2); }
 @Test @DisplayName("UT-BE-ROBOT-006 로봇 세트 작업을 종료하고 충전을 시작한다") void finishSet(){ when(robotMapper.updateSetStatus(3,"WORKING","CHARGING")).thenReturn(2); assertThat(service.finishSet(3)).isEqualTo(2); }
 @Test @DisplayName("UT-BE-ROBOT-007 충전 대상이 없으면 갱신하지 않는다") void noCharging(){ when(robotMapper.findChargingRobots()).thenReturn(List.of()); assertThat(service.chargeIdleRobots()).isZero(); }
 @Test @DisplayName("UT-BE-ROBOT-008 충전량과 저전력 복구·완충 상태를 계산한다") void charging(){ RobotDTO low=robot(1,"LOW_BATTERY",29); RobotDTO full=robot(2,"CHARGING",99.8); when(robotMapper.findChargingRobots()).thenReturn(List.of(low,full)); when(robotMapper.updateChargingState(any())).thenReturn(1); assertThat(service.chargeIdleRobots()).isEqualTo(2); verify(robotMapper).updateChargingState(argThat(d->d.getRobotNo()==1&&d.getRobotStatus().equals("LOW_BATTERY")&&d.getBatteryLevel().equals(new BigDecimal("29.5")))); verify(robotMapper).updateChargingState(argThat(d->d.getRobotNo()==2&&d.getRobotStatus().equals("STANDBY")&&d.getBatteryLevel().compareTo(new BigDecimal("100"))==0)); }
 @Test @DisplayName("UT-BE-ROBOT-009 로봇 상태를 번호와 함께 갱신한다") void updateState(){ RobotDTO d=new RobotDTO(); when(robotMapper.updateState(d)).thenReturn(1); assertThat(service.updateState(7,d)).isEqualTo(1); assertThat(d.getRobotNo()).isEqualTo(7); }
 @Test @DisplayName("UT-BE-ROBOT-010 로봇 점검을 완료한다") void maintenance(){ when(robotMapper.completeMaintenance(7)).thenReturn(1); assertThat(service.completeMaintenance(7)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-ROBOT-011 대기 작업이 없으면 배정하지 않는다") void noWaiting(){ when(robotTaskMapper.findNextWaitingTask()).thenReturn(null); assertThat(service.dispatchWaitingTasks()).isZero(); }
 @Test @DisplayName("UT-BE-ROBOT-012 사용 가능한 세트가 없으면 대기 작업을 유지한다") void noSet(){ RobotTaskDTO t=task(1,"PARK_IN","B1-IN1-01","B1-P01"); when(robotTaskMapper.findNextWaitingTask()).thenReturn(t); when(robotTaskMapper.detail(1)).thenReturn(t); when(robotMapper.findAvailableSetNo(1)).thenReturn(null); assertThat(service.dispatchWaitingTasks()).isZero(); verify(robotTaskMapper,never()).assignSet(anyLong(),anyInt()); }
 @Test @DisplayName("UT-BE-ROBOT-013 세트 시작 또는 작업 배정 실패를 거부한다") void dispatchFailures(){ RobotTaskDTO t=task(1,"PARK_IN","B1-IN1-01","B1-P01"); when(robotTaskMapper.findNextWaitingTask()).thenReturn(t); when(robotTaskMapper.detail(1)).thenReturn(t); when(robotMapper.findAvailableSetNo(1)).thenReturn(1); when(robotMapper.startSet(1)).thenReturn(1); assertThatThrownBy(()->service.dispatchWaitingTasks()).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); when(robotMapper.startSet(1)).thenReturn(2); when(robotTaskMapper.assignSet(1,1)).thenReturn(0); assertThatThrownBy(()->service.dispatchWaitingTasks()).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-ROBOT-014 실행 작업이 없으면 진행하지 않는다") void noRunning(){ when(robotTaskMapper.findRunningTasks()).thenReturn(List.of()); assertThat(service.processRunningTasks()).isZero(); }
 @Test @DisplayName("UT-BE-ROBOT-015 단계가 없거나 시간이 남은 작업은 진행하지 않는다") void runningNotReady(){ RobotTaskDTO noPhase=new RobotTaskDTO(); RobotTaskDTO waiting=new RobotTaskDTO(); waiting.setTaskPhase("LIFTING"); waiting.setPhaseUpdatedAt(OffsetDateTime.now()); when(robotTaskMapper.findRunningTasks()).thenReturn(List.of(noPhase,waiting)); when(robotTaskService.phaseDurationMs(waiting)).thenReturn(5000); assertThat(service.processRunningTasks()).isZero(); }
 @Test @DisplayName("UT-BE-ROBOT-016 로봇을 등록한다") void signup(){ RobotDTO d=new RobotDTO(); when(robotMapper.insert(d)).thenReturn(1); assertThat(service.signUp(d)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-ROBOT-017 로봇을 삭제한다") void delete(){ when(robotMapper.delete(8)).thenReturn(1); assertThat(service.delete(8)).isEqualTo(1); }
 private RobotDTO robot(long no,String status,double battery){ RobotDTO d=new RobotDTO(); d.setRobotNo(no); d.setRobotStatus(status); d.setBatteryLevel(BigDecimal.valueOf(battery)); return d; }
 private RobotTaskDTO task(long no,String type,String pickup,String dropoff){ RobotTaskDTO d=new RobotTaskDTO(); d.setTaskNo(no); d.setTaskType(type); d.setPickupSpaceCode(pickup); d.setDropoffSpaceCode(dropoff); return d; }
}
