package api.gate_p;
import api.carlog_p.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.http.HttpStatus; import org.springframework.scheduling.TaskScheduler; import org.springframework.web.server.ResponseStatusException; import java.time.Instant; import java.util.List; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class GateServiceTest {
 @Mock GateMapper gateMapper; @Mock CarLogMapper carLogMapper; @Mock TaskScheduler taskScheduler; @InjectMocks GateService service;
 @Test @DisplayName("UT-BE-GATE-001 | 조회 조건으로 게이트 목록을 반환한다") void listservice(){ GateDTO q=new GateDTO(); List<GateDTO> expected=List.of(q); when(gateMapper.list(q)).thenReturn(expected); assertThat(service.listservice(q)).isSameAs(expected); verify(gateMapper).list(q); }
 @Test @DisplayName("UT-BE-GATE-002 | 신규 게이트 등록 결과를 반환한다") void signUp(){ GateDTO d=new GateDTO(); when(gateMapper.insert(d)).thenReturn(1); assertThat(service.signUp(d)).isEqualTo(1); verify(gateMapper).insert(d); }
 @Test @DisplayName("UT-BE-GATE-003 | 게이트 번호로 삭제 결과를 반환한다") void delete(){ when(gateMapper.delete(3)).thenReturn(1); assertThat(service.delete(3)).isEqualTo(1); verify(gateMapper).delete(3); }
 @Test @DisplayName("UT-BE-GATE-004 | 게이트 수정정보를 Mapper에 전달한다") void updateGate(){ GateDTO d=new GateDTO(); when(gateMapper.update(d)).thenReturn(1); assertThat(service.updateGate(d)).isEqualTo(1); verify(gateMapper).update(d); }
 @Test @DisplayName("UT-BE-GATE-005 | 관리자 게이트 상태변경을 Mapper에 전달한다") void updateStatus(){ GateDTO d=new GateDTO(); when(gateMapper.updateStatus(d)).thenReturn(1); assertThat(service.updateStatus(d)).isEqualTo(1); verify(gateMapper).updateStatus(d); }
 @Test @DisplayName("UT-BE-GATE-006 | 게이트 열기 상태값 1을 저장한다") void open(){ when(gateMapper.updateStatus(any())).thenReturn(1); assertThat(service.open(7)).isEqualTo(1); verify(gateMapper).updateStatus(argThat(d -> d.getGateNo()==7 && d.getGateStatus()==1)); }
 @Test @DisplayName("UT-BE-GATE-007 | 게이트 닫기 상태값 0을 저장한다") void close(){ when(gateMapper.updateStatus(any())).thenReturn(1); assertThat(service.close(7)).isEqualTo(1); verify(gateMapper).updateStatus(argThat(d -> d.getGateNo()==7 && d.getGateStatus()==0)); }
 @Test @DisplayName("UT-BE-GATE-008 | 5초 후 게이트를 닫는 작업을 예약한다") void scheduleClose(){ ArgumentCaptor<Runnable> task=ArgumentCaptor.forClass(Runnable.class); when(taskScheduler.schedule(task.capture(),any(Instant.class))).thenReturn(null); service.scheduleClose(7); when(gateMapper.updateStatus(any())).thenReturn(1); task.getValue().run(); verify(gateMapper).updateStatus(argThat(d -> d.getGateNo()==7 && d.getGateStatus()==0)); }
 @Test @DisplayName("UT-BE-GATE-009 | 주차기록과 1번 키오스크에 맞는 출차 게이트를 반환한다") void findExitGateNo_kiosk1(){ CarLogDTO log=new CarLogDTO(); log.setParkingNo(10); when(carLogMapper.detail(1)).thenReturn(log); GateDTO found=new GateDTO(); found.setGateNo(9); when(gateMapper.list(any())).thenReturn(List.of(found)); assertThat(service.findExitGateNo(1,1)).isEqualTo(9); verify(gateMapper).list(argThat(d -> d.getParkingNo()==10 && "Out".equals(d.getGateType()) && "B1-OUT-1".equals(d.getGateCode()))); }
 @Test @DisplayName("UT-BE-GATE-010 | 2번 키오스크는 두 번째 B1 출차 게이트 코드를 사용한다") void findExitGateNo_kiosk2(){ CarLogDTO log=new CarLogDTO(); log.setParkingNo(10); when(carLogMapper.detail(1)).thenReturn(log); GateDTO found=new GateDTO(); found.setGateNo(8); when(gateMapper.list(any())).thenReturn(List.of(found)); assertThat(service.findExitGateNo(1,2)).isEqualTo(8); verify(gateMapper).list(argThat(d -> "B1-OUT-2".equals(d.getGateCode()))); }
 @Test @DisplayName("UT-BE-GATE-011 | 잘못된 입출차 기록번호를 거부한다") void findExitGateNo_invalid(){ assertStatus(HttpStatus.BAD_REQUEST,() -> service.findExitGateNo(0,1)); verifyNoInteractions(carLogMapper,gateMapper); }
 @Test @DisplayName("UT-BE-GATE-012 | 입출차 기록이나 출차 게이트가 없으면 404로 처리한다") void findExitGateNo_missing(){ when(carLogMapper.detail(1)).thenReturn(null); assertStatus(HttpStatus.NOT_FOUND,() -> service.findExitGateNo(1,1)); CarLogDTO log=new CarLogDTO(); log.setParkingNo(10); when(carLogMapper.detail(2)).thenReturn(log); when(gateMapper.list(any())).thenReturn(List.of()); assertStatus(HttpStatus.NOT_FOUND,() -> service.findExitGateNo(2,1)); }
 @Test @DisplayName("UT-BE-GATE-013 | 카메라 번호로 연결 게이트를 반환한다") void findByCameraNo(){ GateDTO expected=new GateDTO(); when(gateMapper.findByCameraNo(3)).thenReturn(expected); assertThat(service.findByCameraNo(3)).isSameAs(expected); verify(gateMapper).findByCameraNo(3); }
 private void assertStatus(HttpStatus status,Runnable action){ ResponseStatusException e=catchThrowableOfType(action::run,ResponseStatusException.class); assertThat(e).isNotNull(); assertThat(e.getStatusCode()).isEqualTo(status); }
}
