package api.robot_task_p;
import api.parking_space_p.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import java.util.List; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class RobotTaskServiceTest {
 @Mock RobotTaskMapper mapper; @Mock ParkingSpaceService parkingSpaceService; @InjectMocks RobotTaskService service;
 @Test @DisplayName("UT-BE-ROBOT-TASK-001 목록에 단계 소요시간을 계산한다") void list(){ RobotTaskDTO d=task("LIFTING"); when(mapper.list()).thenReturn(List.of(d)); assertThat(service.list().get(0).getPhaseDurationMs()).isEqualTo(5000); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-002 상세에 단계 소요시간을 계산하고 미존재 시 null을 반환한다") void detail(){ RobotTaskDTO d=task("PICKUP_POSITIONING"); when(mapper.detail(1)).thenReturn(d); assertThat(service.detail(1).getPhaseDurationMs()).isEqualTo(3000); assertThat(service.detail(2)).isNull(); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-003 단계별 고정시간과 미지정 단계 시간을 계산한다") void fixedDuration(){ RobotTaskDTO d=task(null); assertThat(service.phaseDurationMs(d)).isZero(); d.setTaskPhase("PICKUP_POSITIONING"); assertThat(service.phaseDurationMs(d)).isEqualTo(3000); d.setTaskPhase("LOWERING"); assertThat(service.phaseDurationMs(d)).isEqualTo(5000); d.setTaskPhase("WAITING"); assertThat(service.phaseDurationMs(d)).isZero(); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-004 세 이동 단계 시간을 최소·최대 범위로 계산한다") void movementDuration(){ RobotTaskDTO d=task("MOVING_TO_PICKUP"); d.setSetNo(1); d.setPickupSpaceCode("B1-IN1-01"); assertThat(service.phaseDurationMs(d)).isBetween(3000,15000); d.setTaskPhase("MOVING_TO_DROPOFF"); d.setDropoffSpaceCode("B1-P80"); assertThat(service.phaseDurationMs(d)).isBetween(3000,15000); d.setTaskPhase("RETURNING_HOME"); assertThat(service.phaseDurationMs(d)).isBetween(3000,15000); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-005 기존 입차 작업을 재사용한다") void existingParkIn(){ RobotTaskDTO x=new RobotTaskDTO(); when(mapper.findActiveTask(1,"PARK_IN")).thenReturn(x); assertThat(service.createParkInTask(1)).isSameAs(x); verifyNoInteractions(parkingSpaceService); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-006 입차대기면과 빈 주차면으로 입차 작업을 생성한다") void createParkIn(){ ParkingSpaceDTO pickup=space(1L,1,1,"ENTRY_WAIT"); ParkingSpaceDTO drop=space(2L,1,1,"PARKING"); when(parkingSpaceService.findByCarLogNo(1)).thenReturn(pickup); when(parkingSpaceService.findEmptyParkingSpace(1,1)).thenReturn(drop); stubInsert(); RobotTaskDTO result=service.createParkInTask(1); assertThat(result.getTaskType()).isEqualTo("PARK_IN"); assertThat(result.getPriority()).isZero(); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-007 입차 작업은 잘못된 출발면과 빈 주차면 부재를 거부한다") void parkInFailures(){ when(parkingSpaceService.findByCarLogNo(1)).thenReturn(null); assertThatThrownBy(()->service.createParkInTask(1)).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); ParkingSpaceDTO pickup=space(1L,1,1,"ENTRY_WAIT"); when(parkingSpaceService.findByCarLogNo(1)).thenReturn(pickup); assertThatThrownBy(()->service.createParkInTask(1)).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-008 기존 출차 작업을 재사용한다") void existingParkOut(){ RobotTaskDTO x=new RobotTaskDTO(); when(mapper.findActiveTask(2,"PARK_OUT")).thenReturn(x); assertThat(service.createParkOutTask(2,9)).isSameAs(x); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-009 주차면과 같은 주차장의 출차대기면으로 출차 작업을 생성한다") void createParkOut(){ ParkingSpaceDTO pickup=space(1L,1,1,"PARKING"); ParkingSpaceDTO drop=space(2L,1,9,"EXIT_WAIT"); when(parkingSpaceService.findByCarLogNo(2)).thenReturn(pickup); when(parkingSpaceService.findEmptyWaitingSpace(9,"EXIT_WAIT")).thenReturn(drop); stubInsert(); RobotTaskDTO result=service.createParkOutTask(2,9); assertThat(result.getTaskType()).isEqualTo("PARK_OUT"); assertThat(result.getPriority()).isEqualTo(10); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-010 출차 작업은 잘못된 출발면과 다른 주차장 대기면을 거부한다") void parkOutFailures(){ when(parkingSpaceService.findByCarLogNo(2)).thenReturn(null); assertThatThrownBy(()->service.createParkOutTask(2,9)).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); ParkingSpaceDTO pickup=space(1L,1,1,"PARKING"); when(parkingSpaceService.findByCarLogNo(2)).thenReturn(pickup); when(parkingSpaceService.findEmptyWaitingSpace(9,"EXIT_WAIT")).thenReturn(space(2L,2,9,"EXIT_WAIT")); assertThatThrownBy(()->service.createParkOutTask(2,9)).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-011 기존 재주차 작업을 재사용한다") void existingRepark(){ RobotTaskDTO x=new RobotTaskDTO(); when(mapper.findActiveTask(3,"PARK_IN")).thenReturn(x); assertThat(service.createReparkTask(3)).isSameAs(x); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-012 출차대기 차량을 빈 주차면으로 재주차한다") void createRepark(){ when(parkingSpaceService.findByCarLogNo(3)).thenReturn(space(1L,1,9,"EXIT_WAIT")); when(parkingSpaceService.findEmptyParkingSpace(1,9)).thenReturn(space(2L,1,9,"PARKING")); stubInsert(); assertThat(service.createReparkTask(3).getTaskType()).isEqualTo("PARK_IN"); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-013 재주차는 잘못된 출발면과 빈 주차면 부재를 거부한다") void reparkFailures(){ when(parkingSpaceService.findByCarLogNo(3)).thenReturn(null); assertThatThrownBy(()->service.createReparkTask(3)).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); when(parkingSpaceService.findByCarLogNo(3)).thenReturn(space(1L,1,9,"EXIT_WAIT")); assertThatThrownBy(()->service.createReparkTask(3)).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-ROBOT-TASK-014 시간초과 차량별 재주차를 계속하고 성공 건수만 반환한다") void timedOut(){ when(parkingSpaceService.findTimedOutExitWaitCarLogNos()).thenReturn(List.of(1,2)); when(parkingSpaceService.findByCarLogNo(1)).thenReturn(space(1L,1,9,"EXIT_WAIT")); when(parkingSpaceService.findEmptyParkingSpace(1,9)).thenReturn(space(2L,1,9,"PARKING")); when(parkingSpaceService.findByCarLogNo(2)).thenReturn(null); stubInsert(); assertThat(service.createTimedOutReparkTasks()).isEqualTo(1); }
 private void stubInsert(){ doAnswer(i->{ RobotTaskDTO d=i.getArgument(0); d.setTaskNo(99L); when(mapper.detail(99L)).thenReturn(d); return 1; }).when(mapper).insert(any()); }
 private RobotTaskDTO task(String phase){ RobotTaskDTO d=new RobotTaskDTO(); d.setTaskPhase(phase); return d; }
 private ParkingSpaceDTO space(long no,int parking,int gate,String type){ ParkingSpaceDTO d=new ParkingSpaceDTO(); d.setSpaceNo(no); d.setParkingNo(parking); d.setGateNo(gate); d.setSpaceType(type); return d; }
}
