package api.board_p;
import org.junit.jupiter.api.*; import org.springframework.core.io.Resource; import org.springframework.http.MediaType; import org.springframework.security.authentication.UsernamePasswordAuthenticationToken; import org.springframework.security.core.Authentication; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.server.ResponseStatusException; import java.util.List; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
class BoardControllerTest {
 BoardService service=mock(BoardService.class); BoardController controller=new BoardController(service);
 @Test @DisplayName("UT-BE-BOARD-CTRL-001 관리자가 공지사항을 등록한다") void create(){ BoardDTO d=new BoardDTO(); MultipartFile f=mock(MultipartFile.class); when(service.create(d,f,"admin")).thenReturn(d); assertThat(controller.create(d,f,auth("admin","ADMIN"))).isSameAs(d); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-002 관리자와 입주민의 공개범위를 구분해 목록을 조회한다") void list(){ controller.list(auth("admin","ADMIN")); verify(service).list(false); controller.list(auth("user","RESIDENT")); verify(service).list(true); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-003 관리자와 입주민의 공개범위를 구분해 상세를 조회한다") void detail(){ controller.detail(1,auth("admin","ADMIN")); verify(service).detail(1,false); controller.detail(1,auth("user","RESIDENT")); verify(service).detail(1,true); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-004 공지 이미지를 미디어타입과 함께 반환한다") void image(){ Resource r=mock(Resource.class); when(service.image(1,true)).thenReturn(new BoardService.BoardImage(r,MediaType.IMAGE_PNG)); assertThat(controller.image(1,auth("user","RESIDENT")).getBody()).isSameAs(r); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-005 관리자가 공지사항을 수정한다") void update(){ BoardDTO d=new BoardDTO(); when(service.update(1,d,null)).thenReturn(d); assertThat(controller.update(1,d,null,auth("admin","ADMIN"))).isSameAs(d); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-006 관리자가 공지사항을 삭제한다") void delete(){ controller.delete(1,auth("admin","ADMIN")); verify(service).delete(1); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-007 로그인 사용자의 댓글 작성자명을 조회한다") void writer(){ when(service.commentWriterName("user")).thenReturn("김입주"); assertThat(controller.commentWriterName(auth("user","RESIDENT"))).isEqualTo("김입주"); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-008 접근 가능한 공지의 댓글을 조회한다") void comments(){ when(service.commentList(1,"user")).thenReturn(List.of()); assertThat(controller.comments(1,auth("user","RESIDENT"))).isEmpty(); verify(service).detail(1,true); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-009 접근 가능한 공지에 댓글을 등록한다") void createComment(){ BoardDTO d=new BoardDTO(); when(service.createComment(1,d,"user")).thenReturn(d); assertThat(controller.createComment(1,d,auth("user","RESIDENT"))).isSameAs(d); verify(service).detail(1,true); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-010 작성자 댓글을 수정한다") void updateComment(){ BoardDTO d=new BoardDTO(); when(service.updateComment(1,2,d,"user")).thenReturn(d); assertThat(controller.updateComment(1,2,d,auth("user","RESIDENT"))).isSameAs(d); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-011 작성자 댓글을 권한 정보와 함께 삭제한다") void deleteComment(){ controller.deleteComment(1,2,auth("admin","ADMIN")); verify(service).deleteComment(1,2,"admin",true); controller.deleteComment(1,3,auth("user","RESIDENT")); verify(service).deleteComment(1,3,"user",false); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-012 미인증 또는 허용되지 않은 역할의 목록 조회를 거부한다") void listAuthorization(){ assertThatThrownBy(()->controller.list(null)).isInstanceOf(ResponseStatusException.class); assertThatThrownBy(()->controller.list(auth("guest","GUEST"))).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-BOARD-CTRL-013 입주민의 공지 등록을 거부한다") void createAuthorization(){ assertThatThrownBy(()->controller.create(new BoardDTO(),null,auth("user","RESIDENT"))).isInstanceOf(ResponseStatusException.class); }
 private Authentication auth(String id,String role){ return new UsernamePasswordAuthenticationToken(id,"",List.of(new SimpleGrantedAuthority(role))); }
}
