package api.openapi_p.aichat_p;
import api.faq_p.*; import org.junit.jupiter.api.*; import org.springframework.test.util.ReflectionTestUtils; import org.springframework.web.server.ResponseStatusException; import java.util.List; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
class AiChatServiceTest {
 @Test @DisplayName("UT-BE-AICHAT-001 빈 질문을 거부한다") void blankQuestion(){ AiChatService s=new AiChatService(); assertThatThrownBy(() -> s.chat(null)).isInstanceOf(ResponseStatusException.class); AiChatRequestDTO q=new AiChatRequestDTO(); q.setQuestion(" "); assertThatThrownBy(() -> s.chat(q)).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-AICHAT-002 질문은 500자를 허용하고 초과하면 거부한다") void questionLength(){ AiChatService s=service(List.of()); AiChatRequestDTO ok=new AiChatRequestDTO(); ok.setQuestion("가".repeat(500)); assertThat(s.chat(ok).getResponseType()).isEqualTo("AI_UNAVAILABLE"); AiChatRequestDTO tooLong=new AiChatRequestDTO(); tooLong.setQuestion("가".repeat(501)); assertThatThrownBy(() -> s.chat(tooLong)).isInstanceOf(ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-AICHAT-003 API 키가 없으면 일치하는 FAQ 답변으로 대체한다") void faqFallback(){ FaqDTO f=new FaqDTO(); f.setQuestion("주차 요금"); f.setAnswer("요금 안내"); AiChatService s=service(List.of(f)); AiChatRequestDTO q=new AiChatRequestDTO(); q.setQuestion("주차 요금?"); assertThat(s.chat(q).getAnswer()).isEqualTo("요금 안내"); assertThat(s.chat(q).isFallback()).isTrue(); }
 @Test @DisplayName("UT-BE-AICHAT-004 API 키와 일치 FAQ가 없으면 이용불가 안내를 반환한다") void unavailableFallback(){ AiChatService s=service(List.of()); AiChatRequestDTO q=new AiChatRequestDTO(); q.setQuestion("개인 차량 상태"); assertThat(s.chat(q).getResponseType()).isEqualTo("AI_UNAVAILABLE"); }
 private AiChatService service(List<FaqDTO> faqs){ AiChatService s=new AiChatService(); FaqService faq=mock(FaqService.class); AiKnowledgeService knowledge=mock(AiKnowledgeService.class); when(faq.list()).thenReturn(faqs); when(knowledge.getDocuments()).thenReturn(List.of()); ReflectionTestUtils.setField(s,"faqService",faq); ReflectionTestUtils.setField(s,"aiKnowledgeService",knowledge); ReflectionTestUtils.setField(s,"apiKey",""); return s; }
}
