package api.cameradata_p;
import api.trash_p.TrashService; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.junit.jupiter.api.io.TempDir; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.security.core.Authentication; import org.springframework.web.multipart.MultipartFile; import java.nio.file.*; import java.util.List; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class CameraDataControllerTest {
 @Mock CameraDataService service; @Mock TrashService trash; @Mock Authentication auth; @InjectMocks CameraDataController controller; @TempDir Path temp;
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-001 촬영 데이터 페이지를 조회한다") void list(){ CameraDataDTO.PageResponse x=mock(CameraDataDTO.PageResponse.class); when(service.page(1,10,"12",1)).thenReturn(x); assertThat(controller.list(1,10,"12",1)).isSameAs(x); }
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-002 OCR 촬영 파일을 처리한다") void ocr(){ MultipartFile f=mock(MultipartFile.class), crop=mock(MultipartFile.class); CameraDataDTO x=new CameraDataDTO(); when(service.ocr(1,"12가3456",.9,f,crop)).thenReturn(x); assertThat(controller.ocr(1,"12가3456",.9,f,crop)).isSameAs(x); }
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-003 촬영 데이터 상세를 조회한다") void detail(){ CameraDataDTO x=new CameraDataDTO(); when(service.getCameraData(1)).thenReturn(x); assertThat(controller.getCameraData(1)).isSameAs(x); }
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-004 차량번호를 수정한다") void edit(){ CameraDataDTO d=new CameraDataDTO(); when(service.editCarNo(1,d)).thenReturn(d); assertThat(controller.editCarNo(1,d)).isSameAs(d); }
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-005 저신뢰 차량번호 확인 후 게이트를 처리한다") void confirm(){ CameraDataDTO d=new CameraDataDTO(); when(service.confirmLowConfidenceGate(1,d)).thenReturn(d); assertThat(controller.confirmLowConfidenceGate(1,d)).isSameAs(d); }
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-006 로그인 관리자가 일반 방문 게이트를 연다") void visitGate(){ when(auth.getName()).thenReturn("admin"); when(service.openVisitGateByCameraData("admin",1)).thenReturn(1); assertThat(controller.openVisitGate(auth,1)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-007 로그인 관리자가 긴급차량 게이트를 연다") void emergencyGate(){ when(auth.getName()).thenReturn("admin"); when(service.openEmergencyGateByCameraData("admin",1)).thenReturn(1); assertThat(controller.openEmergencyGate(auth,1)).isEqualTo(1); }
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-008 차량번호로 촬영 데이터를 검색한다") void search(){ List<CameraDataDTO>x=List.of(); when(service.searchByCarNo("3456")).thenReturn(x); assertThat(controller.search("3456")).isSameAs(x); }
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-009 촬영 데이터를 지난 기록으로 이동한다") void delete(){ assertThat(controller.delete(1)).isEqualTo(1); verify(trash).moveCameraData(1,"MANUAL"); }
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-010 원본 이미지를 응답한다") void image() throws Exception { Path p=Files.writeString(temp.resolve("image.bin"),"x"); when(service.getCameraImagePath(1)).thenReturn(p); assertThat(controller.getImage(1).getBody()).isNotNull(); }
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-011 차량번호 영역 이미지를 응답한다") void cropImage() throws Exception { Path p=Files.writeString(temp.resolve("crop.bin"),"x"); when(service.getCameraCropImagePath(1)).thenReturn(p); assertThat(controller.getCropImage(1).getBody()).isNotNull(); }
 @Test @DisplayName("UT-BE-CAMERADATA-CTRL-012 촬영 데이터 메모를 수정한다") void note(){ CameraDataDTO d=new CameraDataDTO(); d.setCamNote("memo"); when(service.updateNote(1,"memo")).thenReturn(d); assertThat(controller.updateNote(1,d)).isSameAs(d); }
}
