package api.gate_pdm_p;
import api.predictive_maintenance_p.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import java.util.List; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class GatePdmServiceTest {
 @Mock GatePdmMapper mapper; @Mock PredictiveMaintenanceClient client; @Mock PdmActionAuthorizationService auth; @InjectMocks GatePdmService service;
 @Test @DisplayName("UT-BE-GATE-PDM-001 저장된 게이트 예측 목록을 반환한다") void list(){ GatePdmDTO d=new GatePdmDTO(); when(mapper.list()).thenReturn(List.of(d)); assertThat(service.list()).containsExactly(d); verify(mapper).list(); }
 @Test @DisplayName("UT-BE-GATE-PDM-006 예측 번호로 게이트 상세 결과를 반환한다") void detail(){ GatePdmDTO d=new GatePdmDTO(); when(mapper.detail(1)).thenReturn(d); assertThat(service.detail(1)).isSameAs(d); verify(mapper).detail(1); }
 @Test @DisplayName("UT-BE-GATE-PDM-007 직접 입력한 게이트 예측 결과를 저장한다") void savePrediction(){ GatePdmDTO d=new GatePdmDTO(); when(mapper.savePrediction(d)).thenReturn(1); assertThat(service.savePrediction(d)).isEqualTo(1); verify(mapper).savePrediction(d); }
 @Test @DisplayName("UT-BE-GATE-PDM-002 일괄 분석 응답이 없으면 빈 목록을 반환한다") void nullAll(){ when(client.predictNextGates()).thenReturn(null); assertThat(service.analyzeAll()).isEmpty(); }
 @Test @DisplayName("UT-BE-GATE-PDM-003 메모리 예측 이력 초기값은 빈 목록이다") void emptyMemory(){ assertThat(service.getLatestPredictions()).isEmpty(); assertThat(service.getRecentPredictions(1)).isEmpty(); }
 @Test @DisplayName("UT-BE-GATE-PDM-004 단건 정상 분석을 최신·최근 이력에 반영하고 시간별 저장한다") void analyzeAndHourlySave(){ PredictiveMaintenanceResponseDTO r=normal("GATE-001"); when(client.predictNextGate()).thenReturn(r); assertThat(service.analyzeOne()).isSameAs(r); assertThat(service.getLatestPredictions()).hasSize(1); service.saveHourlyNormalPredictions(); verify(mapper).savePrediction(argThat(d -> d.getGateNo()==1)); }
 @Test @DisplayName("UT-BE-GATE-PDM-005 없는 예측 결과의 조치 완료를 거부한다") void completeMissing(){ assertThatThrownBy(() -> service.completeAction(9,"점검","admin")).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); verifyNoInteractions(client,auth); }
 @Test @DisplayName("UT-BE-GATE-PDM-008 조치가 필요한 위험 분석을 저장하고 알림을 발송한다") void dangerAlert(){ PredictiveMaintenanceResponseDTO r=normal("GATE-002"); r.setRiskLevel("위험"); r.setActionRequired(true); when(client.predictNextGate()).thenReturn(r); when(mapper.savePrediction(any())).thenReturn(1); service.analyzeOne(); verify(auth).sendDangerAlert(eq("게이트 GATE-02"),eq(r.getSensorValues())); verify(mapper).findActiveAction(2); }
 @Test @DisplayName("UT-BE-GATE-PDM-009 일괄 분석 결과를 게이트 번호순 최신 상태로 제공한다") void analyzeAll(){ List<PredictiveMaintenanceResponseDTO> rs=List.of(normal("GATE-002"),normal("GATE-001")); when(client.predictNextGates()).thenReturn(rs); assertThat(service.analyzeAll()).isSameAs(rs); assertThat(service.getLatestPredictions()).extracting(GatePdmDTO::getGateNo).containsExactly(1,2); }
 @Test @DisplayName("UT-BE-GATE-PDM-010 잘못된 게이트 장비 코드를 거부한다") void invalidEquipment(){ PredictiveMaintenanceResponseDTO r=normal("GATE-013"); when(client.predictNextGate()).thenReturn(r); assertThatThrownBy(service::analyzeOne).isInstanceOf(IllegalArgumentException.class); verifyNoInteractions(mapper); }
 @Test @DisplayName("UT-BE-GATE-PDM-011 활성 위험 조치를 완료하고 최신 상태를 갱신한다") void completeAction(){ GatePdmDTO target=danger(2); GatePdmDTO completed=new GatePdmDTO(); completed.setGateNo(2); completed.setActionStatus("COMPLETED"); when(mapper.detail(5)).thenReturn(target,completed); when(auth.requireMemberNo("admin")).thenReturn(7); when(auth.normalizeActionNote(" 점검 ")).thenReturn("점검"); when(mapper.completeAction(5,7,"점검")).thenReturn(1); assertThat(service.completeAction(5," 점검 ","admin")).isSameAs(completed); verify(client).completeGateAction(2); }
 @Test @DisplayName("UT-BE-GATE-PDM-012 조치 대상이 아니거나 DB 갱신에 실패하면 충돌로 처리한다") void completeConflict(){ GatePdmDTO normal=new GatePdmDTO(); normal.setRiskLevel("정상"); normal.setActionStatus("NOT_REQUIRED"); when(mapper.detail(1)).thenReturn(normal); assertThatThrownBy(() -> service.completeAction(1,"x","admin")).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); GatePdmDTO target=danger(2); when(mapper.detail(2)).thenReturn(target); when(auth.requireMemberNo("admin")).thenReturn(7); when(auth.normalizeActionNote("x")).thenReturn("x"); when(mapper.completeAction(2,7,"x")).thenReturn(0); assertThatThrownBy(() -> service.completeAction(2,"x","admin")).isInstanceOf(org.springframework.web.server.ResponseStatusException.class); }
 @Test @DisplayName("UT-BE-GATE-PDM-013 시간별 저장은 최신 정상 결과만 저장한다") void hourlyOnlyNormal(){ PredictiveMaintenanceResponseDTO normal=normal("GATE-001"); PredictiveMaintenanceResponseDTO warning=normal("GATE-002"); warning.setRiskLevel("주의"); when(client.predictNextGates()).thenReturn(List.of(normal,warning)); when(mapper.savePrediction(any())).thenReturn(1); service.analyzeAll(); clearInvocations(mapper); service.saveHourlyNormalPredictions(); verify(mapper).savePrediction(argThat(d -> d.getGateNo()==1 && "정상".equals(d.getRiskLevel()))); verifyNoMoreInteractions(mapper); }
 private GatePdmDTO danger(int no){ GatePdmDTO d=new GatePdmDTO(); d.setGateNo(no); d.setRiskLevel("위험"); d.setActionStatus("ACTION_REQUIRED"); return d; }
 private PredictiveMaintenanceResponseDTO normal(String no){ PredictiveMaintenanceResponseDTO r=new PredictiveMaintenanceResponseDTO(); r.setEquipmentNo(no); r.setRiskLevel("정상"); r.setRiskProbability(.9); r.setProbabilities(java.util.Map.of("정상",.9,"주의",.08,"위험",.02)); r.setSensorValues(java.util.Map.of()); r.setPredictedAt(java.time.LocalDateTime.now()); return r; }
}
